POST http://localhost:5210/api/authentication/register
Content-Type: application/json

{
  "FirstName": "aksdfnkadsnf",
  "LastName": "asdfkasnf1392049", 
  "Email": "1@gmail.com",
  "Password": "sdf"
}