POST http://localhost:5210/api/authentication/register
Content-Type: application/json

{
  "FirstName": "userWithToken",
  "LastName": "lastNameWithToken", 
  "Email": "token@gmail.com",
  "Password": "tloken"
}